In [10]:
import numpy as np 

In [11]:
a = np.ones((4,5))
b = np.zeros((4,5))
c = a + a

In [14]:
c

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [15]:
z = np.stack((a, b, c))

In [16]:
z

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [6]:
z.shape

(3, 4, 5)

In [17]:
np.rollaxis(z, 0,2).shape

(4, 3, 5)

In [18]:
np.rollaxis(z, 0,2)

array([[[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [2., 2., 2., 2., 2.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [2., 2., 2., 2., 2.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [2., 2., 2., 2., 2.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [2., 2., 2., 2., 2.]]])